### ISSUE TITLE
Audio cast.

### ISSUE THREAD

**Issue by salamay** [gianlucaparadise/flutter_cast_framework#1]
i want to ask if i can use this to cast audio to chromecast

**Comment by gianlucaparadise** [comment]
I'm not planning to support it, but given the official Google Cast Framework [docs](https://developers.google.com/cast/docs/audio) it **may** be indirectly supported.

You just should make sure of this:
> Warning: Do not send a video stream to an audio-only device; doing so may cause the application to fail.

**N.B.** This plugin is under development and it isn't 100% stable yet.
